export const MOCK_INVERTERS = [
  {
    _id: 'mock-001',
    name: 'Huawei SUN2000-5KTL-M3',
    subtitle: 'String Inverter | 5 kW | Dual MPPT | Residential',
    description:
      'The SUN2000-5KTL-M3 is a high-efficiency residential string inverter from Huawei featuring advanced MPPT tracking, built-in arc fault detection, and seamless integration with the FusionSolar monitoring platform.',
    image: '/inverter3.png',
    gallery: ['/inverter3.png', '/inverter3.png', '/inverter3.png'],
    pdfUrl: 'https://solar.huawei.com/en-GB/download',
    features: [
      'Dual MPPT for flexible system design',
      'Built-in DC switch and arc fault detection',
      'FusionSolar app monitoring',
      'Smart dongle for cloud connectivity',
      'Wide input voltage range 200–1000 V DC',
    ],
    models: ['SUN2000-5KTL-M3', 'SUN2000-6KTL-M3', 'SUN2000-8KTL-M3'],
    specs: [
      { label: 'Power Rating', value: '5 kW' },
      { label: 'Efficiency', value: '98.6%' },
      { label: 'Warranty', value: '10 Years' },
      { label: 'Type', value: 'String Inverter' },
      { label: 'Input Voltage Range', value: '200–1000 V DC' },
      { label: 'Output Voltage', value: '230 V AC' },
      { label: 'Frequency', value: '50/60 Hz' },
      { label: 'Protection Rating', value: 'IP65' },
    ],
    company: {
      _id: 'mock-company-001',
      name: 'Huawei Solar',
      country: 'China',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Huawei_Standard_logo.svg/120px-Huawei_Standard_logo.svg.png',
      color1: 'rgba(220, 38, 38, 1)',
      color2: 'rgba(254, 226, 226, 1)',
      color3: 'rgba(252, 165, 165, 1)',
    },
    warranty: { years: 10, type: 'product' },
    sortOrder: 1,
    createdAt: '2024-01-01',
  },
  {
    _id: 'mock-002',
    name: 'Huawei SUN2000-100KTL-M2',
    description:
      'The SUN2000-100KTL-M2 is a commercial-grade three-phase string inverter designed for large-scale solar power plants, offering high power density and intelligent IV curve diagnostics to maximize energy yield.',
    image: '/inverter3.png',
    pdfUrl: 'https://solar.huawei.com/en-GB/download',
    features: [
      '12 MPPTs for complex rooftops',
      'Smart IV curve diagnostics',
      'Active power control and reactive power compensation',
      'IP65 protection rating',
      'Natural cooling with no moving parts',
    ],
    models: ['SUN2000-100KTL-M2', 'SUN2000-110KTL-M2', 'SUN2000-125KTL-M2'],
    specs: [
      { label: 'Power Rating', value: '100 kW' },
      { label: 'Efficiency', value: '99.0%' },
      { label: 'Warranty', value: '10 Years' },
      { label: 'Type', value: 'Three-Phase String' },
      { label: 'Input Voltage Range', value: '200–1500 V DC' },
      { label: 'Output Voltage', value: '3×400 V AC' },
      { label: 'Frequency', value: '50/60 Hz' },
      { label: 'Protection Rating', value: 'IP65' },
    ],
    company: {
      _id: 'mock-company-001',
      name: 'Huawei Solar',
      country: 'China',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Huawei_Standard_logo.svg/120px-Huawei_Standard_logo.svg.png',
      color1: 'rgba(220, 38, 38, 1)',
      color2: 'rgba(254, 226, 226, 1)',
      color3: 'rgba(252, 165, 165, 1)',
    },
    warranty: { years: 10, type: 'product' },
    sortOrder: 2,
    createdAt: '2024-01-02',
  },
  {
    _id: 'mock-003',
    name: 'SMA Sunny Boy 5.0',
    description:
      "The Sunny Boy 5.0 is a compact, lightweight single-phase inverter from SMA, perfect for residential rooftop solar systems. It features OptiTracks® global peak tracking and Secure Power Supply for off-grid emergency operation.",
    image: '/inverter3.png',
    pdfUrl: 'https://files.sma.de/downloads/SB5.0-1AV-41-DS-en-24W.pdf',
    features: [
      'OptiTracks® global peak MPPT',
      'Secure Power Supply during grid outage',
      'SMA Energy Meter integration',
      'Integrated DC load-break switch',
      'Lightweight design — only 13 kg',
    ],
    models: ['SB 3.0-1AV-41', 'SB 4.0-1AV-41', 'SB 5.0-1AV-41', 'SB 6.0-1AV-41'],
    specs: [
      { label: 'Power Rating', value: '5 kW' },
      { label: 'Efficiency', value: '97.3%' },
      { label: 'Warranty', value: '5 Years' },
      { label: 'Type', value: 'Single-Phase' },
      { label: 'Input Voltage Range', value: '150–750 V DC' },
      { label: 'Output Voltage', value: '230 V AC' },
      { label: 'Frequency', value: '50/60 Hz' },
      { label: 'Weight', value: '13 kg' },
    ],
    company: {
      _id: 'mock-company-002',
      name: 'SMA Solar Technology',
      country: 'Germany',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/SMA_Solar_Technology_AG_Logo.svg/120px-SMA_Solar_Technology_AG_Logo.svg.png',
      color1: 'rgba(22, 163, 74, 1)',
      color2: 'rgba(220, 252, 231, 1)',
      color3: 'rgba(134, 239, 172, 1)',
    },
    warranty: { years: 5, type: 'product' },
    sortOrder: 1,
    createdAt: '2024-01-03',
  },
  {
    _id: 'mock-004',
    name: 'SMA Sunny Tripower 25000TL',
    description:
      'The Sunny Tripower 25000TL is a three-phase commercial string inverter from SMA featuring six MPP trackers, OptiTracks® technology, and an integrated DC switch for commercial and industrial rooftop installations.',
    image: '/inverter3.png',
    pdfUrl: 'https://files.sma.de/downloads/STP25000TL-30-DS-en-25.pdf',
    features: [
      'Six MPP trackers for shade tolerance',
      'OptiTracks® global peak detection',
      'Integrated DC load-break switch',
      'Reactive power supply 24/7',
      'Galvanically isolated transformerless design',
    ],
    models: ['STP 15000TL-30', 'STP 20000TL-30', 'STP 25000TL-30'],
    specs: [
      { label: 'Power Rating', value: '25 kW' },
      { label: 'Efficiency', value: '98.4%' },
      { label: 'Warranty', value: '5 Years' },
      { label: 'Type', value: 'Three-Phase String' },
      { label: 'Input Voltage Range', value: '188–800 V DC' },
      { label: 'Output Voltage', value: '3×400 V AC' },
      { label: 'Frequency', value: '50/60 Hz' },
      { label: 'Protection Rating', value: 'IP65' },
    ],
    company: {
      _id: 'mock-company-002',
      name: 'SMA Solar Technology',
      country: 'Germany',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/SMA_Solar_Technology_AG_Logo.svg/120px-SMA_Solar_Technology_AG_Logo.svg.png',
      color1: 'rgba(22, 163, 74, 1)',
      color2: 'rgba(220, 252, 231, 1)',
      color3: 'rgba(134, 239, 172, 1)',
    },
    warranty: { years: 5, type: 'product' },
    sortOrder: 2,
    createdAt: '2024-01-04',
  },
];

export function getMockInverterById(id) {
  return MOCK_INVERTERS.find((p) => p._id === id) || null;
}
